version: '3.7'

services:
  graphite:
    image: graphiteapp/graphite-statsd
    container_name: graphite
    ports:
      - "8081:80"
      - "2003:2003"
    volumes:
      - ./graphite_data:/opt/graphite/storage

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - graphite
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  grafana_data:
